# Generated by Django 2.1 on 2019-09-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_auto_20190916_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFixedPriceBenefit',
            fields=[
                ('benefit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offer.Benefit')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
                'abstract': False,
            },
            bases=('offer.fixedpricebenefit',),
        ),
    ]
